// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STIVE.API.Database;

#nullable disable

namespace STIVE.API.Migrations
{
    [DbContext(typeof(stive_potion_seller_context))]
    [Migration("20240920142420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("STIVE.API.Models.Bonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("bonus");
                });

            modelBuilder.Entity("STIVE.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("STIVE.API.Models.Potion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PriceCustomer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("potion");
                });

            modelBuilder.Entity("STIVE.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("role");
                });

            modelBuilder.Entity("STIVE.API.Models.Save", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("save");
                });

            modelBuilder.Entity("STIVE.API.Models.SaveHasBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SaveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BonusId");

                    b.HasIndex("SaveId");

                    b.ToTable("saveHasBonus");
                });

            modelBuilder.Entity("STIVE.API.Models.SaveHasPotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PotionCount")
                        .HasColumnType("int");

                    b.Property<int>("PotionId")
                        .HasColumnType("int");

                    b.Property<int>("SaveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PotionId");

                    b.HasIndex("SaveId");

                    b.ToTable("saveHasPotion");
                });

            modelBuilder.Entity("STIVE.API.Models.SaveHasSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SaveId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaveId");

                    b.HasIndex("SupplierId");

                    b.ToTable("saveHasSupplier");
                });

            modelBuilder.Entity("STIVE.API.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PotionId")
                        .HasColumnType("int");

                    b.Property<int>("PriceSupplier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PotionId");

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("STIVE.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("STIVE.API.Models.UserHasRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("userHasRole");
                });

            modelBuilder.Entity("STIVE.API.Models.Save", b =>
                {
                    b.HasOne("STIVE.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STIVE.API.Models.SaveHasBonus", b =>
                {
                    b.HasOne("STIVE.API.Models.Bonus", "Bonus")
                        .WithMany("BonusHasSaves")
                        .HasForeignKey("BonusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STIVE.API.Models.Save", "Save")
                        .WithMany("SaveHasBonuses")
                        .HasForeignKey("SaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bonus");

                    b.Navigation("Save");
                });

            modelBuilder.Entity("STIVE.API.Models.SaveHasPotion", b =>
                {
                    b.HasOne("STIVE.API.Models.Potion", "Potion")
                        .WithMany("SavesHasPotion")
                        .HasForeignKey("PotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STIVE.API.Models.Save", "Save")
                        .WithMany("SaveHasPotions")
                        .HasForeignKey("SaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Potion");

                    b.Navigation("Save");
                });

            modelBuilder.Entity("STIVE.API.Models.SaveHasSupplier", b =>
                {
                    b.HasOne("STIVE.API.Models.Save", "Save")
                        .WithMany("SaveHasSuppliers")
                        .HasForeignKey("SaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STIVE.API.Models.Supplier", "Supplier")
                        .WithMany("SavesHasSupplier")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Save");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("STIVE.API.Models.Supplier", b =>
                {
                    b.HasOne("STIVE.API.Models.Potion", "Potion")
                        .WithMany()
                        .HasForeignKey("PotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Potion");
                });

            modelBuilder.Entity("STIVE.API.Models.UserHasRole", b =>
                {
                    b.HasOne("STIVE.API.Models.Role", "Role")
                        .WithMany("UsersHasRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STIVE.API.Models.User", "User")
                        .WithMany("UserHasRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STIVE.API.Models.Bonus", b =>
                {
                    b.Navigation("BonusHasSaves");
                });

            modelBuilder.Entity("STIVE.API.Models.Potion", b =>
                {
                    b.Navigation("SavesHasPotion");
                });

            modelBuilder.Entity("STIVE.API.Models.Role", b =>
                {
                    b.Navigation("UsersHasRole");
                });

            modelBuilder.Entity("STIVE.API.Models.Save", b =>
                {
                    b.Navigation("SaveHasBonuses");

                    b.Navigation("SaveHasPotions");

                    b.Navigation("SaveHasSuppliers");
                });

            modelBuilder.Entity("STIVE.API.Models.Supplier", b =>
                {
                    b.Navigation("SavesHasSupplier");
                });

            modelBuilder.Entity("STIVE.API.Models.User", b =>
                {
                    b.Navigation("UserHasRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
